spring.datasource.url=jdbc:mysql://localhost:3306/alertmns?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Paris
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
file.upload-dir=/tmp/alertmns-uploads
